project_id = "ierdfxgeectqoekugyvb"

[functions.whatsapp-baileys]
verify_jwt = true

[functions.pakasir-webhook]
verify_jwt = false

[functions.get-device-qr]
verify_jwt = true

[functions.api-device-management]
verify_jwt = false

[functions.admin-broadcast-send]
verify_jwt = true
